management:
  endpoints:
    shutdown:
      enabled: true
    web:
      exposure:
        include: '*'
server:
  port: 9111
spring:
  datasource:
    username: Kurt
    password:
    url: jdbc:mariadb://kurtdb.c8fwy6oulfc7.us-east-2.rds.amazonaws.com:3306/BBS
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: BBS-Service
  h2:
    console:
      enabled: true
      path: /console
